--- 

- name: Download contractor images
  hosts: localhost
  gather_facts: no

  tasks:
  
  - name: Pull an image
    docker_image:
      name: "{{ item }}"
      source: pull
    loop: "{{ lookup('file', 'input.yaml').splitlines() }}"

  - name: Tag and push 
    docker_image:
      name: "{{ item }}"
      repository: "shesterkinvladimir/{{ item }}"
      push: yes
      source: local
    loop: "{{ lookup('file', 'input.yaml').splitlines() }}"

  - name: Remove images without tag 
    docker_image:
      state: absent
      name: "{{ item }}"
    loop: "{{ lookup('file', 'input.yaml').splitlines() }}"

  - name: Remove images with tag 
    docker_image:
      state: absent
      name: "shesterkinvladimir/{{ item }}"
    loop: "{{ lookup('file', 'input.yaml').splitlines() }}"


